import test from "node:test";
import assert from "node:assert/strict";
import {
  chooseCaptionTracks,
  cleanTranscript,
  extractVideoId,
  getYouTubeTranscript,
  parseCaptionPayload,
  parsePlayerResponse,
  sanitizeFilename,
} from "../src/index.js";

const VIDEO_ID = "dQw4w9WgXcQ";

test("extracts IDs from normal, short, mobile, and Shorts URLs", () => {
  const normal = "https:" + "//www.youtube.com/watch?v=" + VIDEO_ID + "&t=1";
  const short = "https:" + "//youtu.be/" + VIDEO_ID + "?si=x";
  const shorts = "https:" + "//youtube.com/shorts/" + VIDEO_ID;
  const mobile = "https:" + "//m.youtube.com/watch?v=" + VIDEO_ID;
  assert.equal(extractVideoId(normal), VIDEO_ID);
  assert.equal(extractVideoId(short), VIDEO_ID);
  assert.equal(extractVideoId(shorts), VIDEO_ID);
  assert.equal(extractVideoId(mobile), VIDEO_ID);
  assert.equal(extractVideoId("متن " + short + " متن"), VIDEO_ID);
});

test("rejects lookalike hosts and malformed IDs", () => {
  assert.equal(extractVideoId("https://youtube.com.evil.test/watch?v=dQw4w9WgXcQ"), null);
  assert.equal(extractVideoId("https://youtube.com/watch?v=short"), null);
  assert.equal(extractVideoId("not a url"), null);
});

test("manual caption tracks are attempted before ASR tracks", () => {
  const tracks = [
    { languageCode: "en", kind: "asr" },
    { languageCode: "fa" },
    { languageCode: "de", kind: "asr" },
    { languageCode: "en" },
  ];
  assert.deepEqual(chooseCaptionTracks(tracks).map((x) => x.kind ?? "manual"), ["manual", "manual", "asr", "asr"]);
});

test("parses json3 and XML caption payloads", () => {
  assert.deepEqual(parseCaptionPayload(JSON.stringify({ events: [{ segs: [{ utf8: "Hello " }, { utf8: "world" }] }] })), ["Hello world"]);
  assert.deepEqual(parseCaptionPayload('<transcript><text start="0">Hello &amp; world</text></transcript>'), ["Hello &amp; world"]);
});

test("cleans timestamps, markup, whitespace, duplicates, and rolling overlap", () => {
  const cleaned = cleanTranscript([
    "00:00:01 <b>Hello</b>   everyone",
    "00:00:01 <b>Hello</b>   everyone",
    "Hello everyone Today we begin",
    "Today we begin now",
    "[00:05] Fish &amp; chips",
  ]);
  assert.equal(cleaned, "Hello everyone\n\nToday we begin\n\nnow\n\nFish & chips");
});

test("sanitizes filenames and provides a fallback", () => {
  assert.equal(sanitizeFilename('  A/B: C?  '), "A B C.txt");
  assert.equal(sanitizeFilename(""), "youtube_transcript.txt");
});

test("parses player response and fetches manual captions first", async () => {
  const player = {
    playabilityStatus: { status: "OK" },
    videoDetails: { title: "Demo" },
    captions: { playerCaptionsTracklistRenderer: { captionTracks: [
      { baseUrl: "https://captions.invalid/auto", languageCode: "en", kind: "asr" },
      { baseUrl: "https://captions.invalid/manual", languageCode: "fa" },
    ] } },
  };
  const html = `<script>var ytInitialPlayerResponse = ${JSON.stringify(player)};</script>`;
  assert.equal(parsePlayerResponse(html).videoDetails.title, "Demo");

  const calls = [];
  const mockFetch = async (url) => {
    calls.push(String(url));
    if (String(url).includes("youtube.com/watch")) return new Response(html, { status: 200 });
    return new Response(JSON.stringify({ events: [{ segs: [{ utf8: "Manual text" }] }] }), { status: 200 });
  };
  const output = await getYouTubeTranscript(VIDEO_ID, mockFetch);
  assert.equal(output.text, "Manual text");
  assert.equal(output.autoGenerated, false);
  assert.match(calls[1], /captions\.invalid\/manual/);
});

test("falls back to auto captions when manual retrieval fails", async () => {
  const player = {
    playabilityStatus: { status: "OK" },
    captions: { playerCaptionsTracklistRenderer: { captionTracks: [
      { baseUrl: "https://captions.invalid/auto", kind: "asr" },
      { baseUrl: "https://captions.invalid/manual" },
    ] } },
  };
  const html = `ytInitialPlayerResponse = ${JSON.stringify(player)};`;
  const mockFetch = async (url) => {
    const value = String(url);
    if (value.includes("youtube.com/watch")) return new Response(html);
    if (value.includes("/manual")) return new Response("blocked", { status: 503 });
    return new Response(JSON.stringify({ events: [{ segs: [{ utf8: "Auto text" }] }] }));
  };
  const output = await getYouTubeTranscript(VIDEO_ID, mockFetch);
  assert.equal(output.text, "Auto text");
  assert.equal(output.autoGenerated, true);
});


test("reports videos without subtitle tracks", async () => {
  const player = {
    playabilityStatus: { status: "OK" },
    captions: { playerCaptionsTracklistRenderer: { captionTracks: [] } },
  };
  const mockFetch = async () => new Response(`ytInitialPlayerResponse = ${JSON.stringify(player)};`);
  await assert.rejects(() => getYouTubeTranscript(VIDEO_ID, mockFetch), /No caption tracks/);
});

test("reports private and deleted videos as unavailable", async () => {
  for (const reason of ["This is a private video", "This video has been removed by the uploader"]) {
    const player = { playabilityStatus: { status: "ERROR", reason } };
    const mockFetch = async () => new Response(`ytInitialPlayerResponse = ${JSON.stringify(player)};`);
    await assert.rejects(() => getYouTubeTranscript(VIDEO_ID, mockFetch), /private|removed/i);
  }
});

test("treats caption transport failure as temporary", async () => {
  const player = {
    playabilityStatus: { status: "OK" },
    captions: { playerCaptionsTracklistRenderer: { captionTracks: [
      { baseUrl: "https://captions.invalid/manual" },
    ] } },
  };
  const html = `ytInitialPlayerResponse = ${JSON.stringify(player)};`;
  const mockFetch = async (url) => String(url).includes("youtube.com/watch")
    ? new Response(html)
    : new Response("temporary", { status: 503 });
  await assert.rejects(() => getYouTubeTranscript(VIDEO_ID, mockFetch), /caption track requests failed/i);
});

test("cleans a long transcript without truncating it", () => {
  const cues = Array.from({ length: 20000 }, (_, index) => `00:00:01 line ${index}`);
  const output = cleanTranscript(cues);
  assert.match(output, /^line 0/);
  assert.match(output, /line 19999$/);
  assert.equal(output.split("\n\n").length, 20000);
});

test("supports concurrent transcript requests without shared mutable state", async () => {
  const player = {
    playabilityStatus: { status: "OK" },
    captions: { playerCaptionsTracklistRenderer: { captionTracks: [
      { baseUrl: "https://captions.invalid/manual" },
    ] } },
  };
  const html = `ytInitialPlayerResponse = ${JSON.stringify(player)};`;
  const mockFetch = async (url) => String(url).includes("youtube.com/watch")
    ? new Response(html)
    : new Response(JSON.stringify({ events: [{ segs: [{ utf8: "Concurrent text" }] }] }));
  const outputs = await Promise.all(Array.from({ length: 25 }, () => getYouTubeTranscript(VIDEO_ID, mockFetch)));
  assert.ok(outputs.every((result) => result.text === "Concurrent text"));
});
