import test from "node:test";
import assert from "node:assert/strict";
import {
  ERROR_CATEGORIES,
  YOUTUBE_CLIENTS,
  YouTubeExtractionError,
  cleanTranscript,
  extractVideoId,
  getYouTubeTranscript,
  isBotDetection,
  parseCaptionPayload,
  rankCaptionTracks,
  sanitizeFilename,
} from "../src/index.js";

const VIDEO_ID = "Qtl8lJwbd4g";
const INNER_TUBE_MARKER = "/youtubei/v1/player";

function youtubeUrl(kind) {
  if (kind === "watch") return "https:" + "//www.youtube.com/watch?v=" + VIDEO_ID;
  if (kind === "short") return "https:" + "//youtu.be/" + VIDEO_ID;
  return "https:" + "//youtube.com/shorts/" + VIDEO_ID;
}

function track(path, extra = {}) {
  return { baseUrl: "https:" + "//captions.test/" + path, languageCode: "en", ...extra };
}

function playerResponse(tracks = [], extra = {}) {
  return {
    playabilityStatus: { status: "OK" },
    videoDetails: { title: "Test Video" },
    captions: { playerCaptionsTracklistRenderer: { captionTracks: tracks, audioTracks: [] } },
    ...extra,
  };
}

function json3(text) {
  return JSON.stringify({ events: [{ segs: [{ utf8: text }] }] });
}

function assertCategory(category) {
  return (error) => error instanceof YouTubeExtractionError && error.category === category;
}

test("parses YouTube watch URL", () => {
  assert.equal(extractVideoId(youtubeUrl("watch")), VIDEO_ID);
});

test("parses youtu.be URL", () => {
  assert.equal(extractVideoId(youtubeUrl("short") + "?si=test"), VIDEO_ID);
});

test("parses Shorts URL and rejects lookalike hosts", () => {
  assert.equal(extractVideoId(youtubeUrl("shorts")), VIDEO_ID);
  assert.equal(extractVideoId("https://youtube.com.evil.test/watch?v=Qtl8lJwbd4g"), null);
  assert.equal(extractVideoId("https://youtube.com/watch?v=short"), null);
});

test("extracts manual captions from InnerTube", async () => {
  const mockFetch = async (url) => {
    if (String(url).includes(INNER_TUBE_MARKER)) return new Response(JSON.stringify(playerResponse([track("manual")]))) ;
    return new Response(json3("Manual transcript"));
  };
  const result = await getYouTubeTranscript(VIDEO_ID, {}, mockFetch);
  assert.equal(result.text, "Manual transcript");
  assert.equal(result.autoGenerated, false);
  assert.equal(result.title, "Test Video");
});

test("extracts auto-generated captions when no manual track exists", async () => {
  const mockFetch = async (url) => {
    if (String(url).includes(INNER_TUBE_MARKER)) return new Response(JSON.stringify(playerResponse([track("auto", { kind: "asr" })])));
    return new Response(json3("Automatic transcript"));
  };
  const result = await getYouTubeTranscript(VIDEO_ID, {}, mockFetch);
  assert.equal(result.text, "Automatic transcript");
  assert.equal(result.autoGenerated, true);
});

test("prefers manual/default captions over ASR", () => {
  const tracks = [
    track("auto", { kind: "asr" }),
    track("manual-fr"),
    track("manual-default"),
  ];
  const renderer = {
    audioTracks: [{ hasDefaultTrack: true, defaultCaptionTrackIndex: 2 }],
  };
  assert.deepEqual(
    rankCaptionTracks(tracks, renderer).map((item) => item.baseUrl.split("/").at(-1)),
    ["manual-default", "manual-fr", "auto"],
  );
});

test("falls through bot-blocked client to the next InnerTube client", async () => {
  const attemptedClients = [];
  const mockFetch = async (url, init = {}) => {
    if (String(url).includes(INNER_TUBE_MARKER)) {
      const client = init.headers["x-youtube-client-name"];
      attemptedClients.push(client);
      if (attemptedClients.length === 1) return new Response("Sign in to confirm you’re not a bot");
      return new Response(JSON.stringify(playerResponse([track("manual")])));
    }
    return new Response(json3("Fallback succeeded"));
  };
  const result = await getYouTubeTranscript(VIDEO_ID, {}, mockFetch);
  assert.equal(result.text, "Fallback succeeded");
  assert.equal(attemptedClients.length, 2);
});

test("classifies no captionTracks after all clients", async () => {
  let attempts = 0;
  const mockFetch = async () => {
    attempts++;
    return new Response(JSON.stringify(playerResponse([])));
  };
  await assert.rejects(() => getYouTubeTranscript(VIDEO_ID, {}, mockFetch), assertCategory(ERROR_CATEGORIES.NO_CAPTIONS));
  assert.equal(attempts, YOUTUBE_CLIENTS.length);
});

test("detects bot wall across all clients", async () => {
  assert.equal(isBotDetection("LOGIN_REQUIRED: request blocked"), true);
  const mockFetch = async () => new Response("Sign in to confirm you're not a bot", { status: 403 });
  await assert.rejects(() => getYouTubeTranscript(VIDEO_ID, {}, mockFetch), assertCategory(ERROR_CATEGORIES.BOT_DETECTION));
});

test("classifies private/unavailable video separately", async () => {
  const payload = {
    playabilityStatus: { status: "ERROR", reason: "This is a private video" },
  };
  const mockFetch = async () => new Response(JSON.stringify(payload));
  await assert.rejects(() => getYouTubeTranscript(VIDEO_ID, {}, mockFetch), assertCategory(ERROR_CATEGORIES.VIDEO_UNAVAILABLE));
});

test("classifies malformed InnerTube JSON as parse error", async () => {
  const mockFetch = async () => new Response("{not valid json", { status: 200 });
  await assert.rejects(() => getYouTubeTranscript(VIDEO_ID, {}, mockFetch), assertCategory(ERROR_CATEGORIES.PARSE_ERROR));
});

test("parses JSON3, WebVTT, and XML captions", () => {
  assert.deepEqual(parseCaptionPayload(json3("Hello world"), "json3"), ["Hello world"]);
  const vtt = "WEBVTT\n\n00:00:00.000 --> 00:00:02.000\nHello VTT\n\n";
  assert.deepEqual(parseCaptionPayload(vtt, "vtt"), ["Hello VTT"]);
  const xml = '<transcript><text start="0">Hello &amp; XML</text></transcript>';
  assert.deepEqual(parseCaptionPayload(xml), ["Hello &amp; XML"]);
});

test("removes timestamps, markup, entities, duplicates, and rolling overlap", () => {
  const cleaned = cleanTranscript([
    "00:00:01 <b>Hello</b> everyone",
    "00:00:01 <b>Hello</b> everyone",
    "Hello everyone Today we begin",
    "Today we begin now",
    "[00:05] Fish &amp; chips",
  ]);
  assert.equal(cleaned, "Hello everyone\n\nToday we begin\n\nnow\n\nFish & chips");
});

test("falls back from failed JSON3 to WebVTT", async () => {
  const formats = [];
  const mockFetch = async (url) => {
    const value = String(url);
    if (value.includes(INNER_TUBE_MARKER)) return new Response(JSON.stringify(playerResponse([track("manual")])));
    const format = new URL(value).searchParams.get("fmt");
    formats.push(format);
    if (format === "json3") return new Response("bad gateway", { status: 502 });
    return new Response("WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nVTT fallback\n", { status: 200 });
  };
  const result = await getYouTubeTranscript(VIDEO_ID, {}, mockFetch);
  assert.equal(result.text, "VTT fallback");
  assert.deepEqual(formats, ["json3", "vtt"]);
});

test("cleans a long transcript without truncation", () => {
  const cues = Array.from({ length: 20000 }, (_, index) => `00:00:01 line ${index}`);
  const output = cleanTranscript(cues);
  assert.match(output, /^line 0/);
  assert.match(output, /line 19999$/);
  assert.equal(output.split("\n\n").length, 20000);
});

test("handles concurrent independent InnerTube requests", async () => {
  const mockFetch = async (url) => String(url).includes(INNER_TUBE_MARKER)
    ? new Response(JSON.stringify(playerResponse([track("manual")])))
    : new Response(json3("Concurrent transcript"));
  const results = await Promise.all(Array.from({ length: 25 }, () => getYouTubeTranscript(VIDEO_ID, {}, mockFetch)));
  assert.ok(results.every((result) => result.text === "Concurrent transcript"));
});

test("sanitizes title filename and uses fallback title", () => {
  assert.equal(sanitizeFilename(' A/B: C? '), "A B C.txt");
  assert.equal(sanitizeFilename(""), "YouTube Transcript.txt");
});
